### ISSUE TITLE
The .open() method does not support an institution_id parameter

### ISSUE THREAD

**Issue by jung35** [pbernasconi/react-plaid-link#43]
I've been using 
``` <PlaidLink institution='ins_1' ...```

But suddenly, I see this error:

```
Error: The .open() method does not support an institution_id parameter. Please contact Plaid Support (https://dashboard.plaid.com/support/new) if this is causing issues.
```

I cant find anywhere on previous version of docs saying something like this even existed (https://plaid.com/docs/api/2017-03-08/)... is this something that was silently removed?

**Comment by jung35** [comment]
@pbernasconi ?

**Comment by pbernasconi** [comment]
Sorry that I have been unresponsive for this repo.

In the next few weeks, I'm planning to move this repo over to the official Plaid organization, and will be addressing this, and the other open issues then!

Stay tuned for an update soon.

**Comment by jung35** [comment]
@pbernasconi no worries! I totally forgot about this and forgot to give an update that the issue was fixed!

It had to do something with our staging token permissions. We had someone at plaid fix it for us!

**Comment by sharan-wednesday** [comment]
This still isn't working. 

I'm currently on version 1.5.0. 

The use case for me is to preselect the institution so that the user can only be authenticated if he has an account with a particular institution.
@pbernasconi

**Comment by jung35** [comment]
@sharan-wednesday use v1.2.0 the institution gets removed v1.3.0 https://github.com/plaid/react-plaid-link/compare/v1.3.0...master#diff-c554f584679e9a2598d83d87b8c16e0fL25

**Comment by ekilah** [comment]
For future readers it doesn't seem like v1.2.0 has this functionality anymore, likely killed server-side or something?
